#!/usr/bin/env python3
"""Generate the manuscript's figures and result tables from real run outputs.

This closes the loop between the pipeline and the paper. Everything it emits is
derived from files the pipeline wrote; nothing is invented. If a run is missing,
the corresponding table cell stays as a visible placeholder rather than being
quietly filled with a plausible-looking number.

Usage, from the KeyPrompt-AD repository root:

    python make_paper_assets.py --runs runs/gemini-flash-4shot \\
                                --sweep runs/sweep/summary.json \\
                                --out paper/

Produces:
    fig_shots.pdf         logical AUROC against reference-shot count
    fig_qualitative.png   contact sheet of predictions over ground truth
    table_main.tex        Table 1, per-category detection
    table_ablation.tex    Table 3, ablations
    table_localisation.tex Table 4, localisation and parse rate
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional

import os

# Categories included in the generated tables. The single-category study reports
# pushpins only; set KEYPROMPT_ALL_CATEGORIES=1 once the others have been run.
_ALL = [
    ("pushpins", "Pushpins"),
    ("screw_bag", "Screw bag"),
    ("splicing_connectors", "Splicing connectors"),
    ("breakfast_box", "Breakfast box"),
    ("juice_bottle", "Juice bottle"),
]
CATEGORIES = _ALL if os.environ.get("KEYPROMPT_ALL_CATEGORIES") else _ALL[:1]

MISSING = r"\nd"  # renders as the red placeholder defined in the manuscript


def cell(value: Optional[float], places: int = 3) -> str:
    """Format a metric, or emit the visible placeholder if it is absent."""
    if value is None:
        return MISSING
    try:
        f = float(value)
    except (TypeError, ValueError):
        return MISSING
    if f != f:  # NaN
        return MISSING
    return f"{f:.{places}f}"


def load_metrics(runs: Path) -> Dict[str, dict]:
    out: Dict[str, dict] = {}
    for key, _ in CATEGORIES:
        p = runs / key / "metrics.json"
        if p.exists():
            out[key] = json.loads(p.read_text())
    return out


# -- tables --------------------------------------------------------------


def table_main(metrics: Dict[str, dict]) -> str:
    rows: List[str] = []
    aurocs: List[float] = []
    for key, label in CATEGORIES:
        m = metrics.get(key, {})
        if isinstance(m.get("auroc"), (int, float)):
            aurocs.append(m["auroc"])
        rows.append(
            f"{label:<20} & {cell(m.get('auroc'))} & {cell(m.get('auroc_logical'))} "
            f"& {cell(m.get('auroc_structural'))} & {cell(m.get('average_precision'))} "
            f"& {cell(m.get('f1_max'))} \\\\"
        )
    mean = f"{sum(aurocs)/len(aurocs):.3f}" if len(aurocs) == len(CATEGORIES) else MISSING
    body = "\n".join(rows)
    return f"""% Generated by make_paper_assets.py -- do not edit by hand.
\\begin{{tabular}}{{@{{}}lccccc@{{}}}}
\\toprule
Category & AUROC & AUROC$_{{\\mathrm{{log}}}}$ & AUROC$_{{\\mathrm{{str}}}}$ & AP & $F_1^{{\\max}}$ \\\\
\\midrule
{body}
\\midrule
Mean                 & {mean} & {MISSING} & {MISSING} & {MISSING} & {MISSING} \\\\
\\botrule
\\end{{tabular}}
"""


def table_localisation(metrics: Dict[str, dict]) -> str:
    rows = []
    for key, label in CATEGORIES:
        m = metrics.get(key, {})
        loc = m.get("localisation") or {}
        rows.append(
            f"{label:<20} & {cell(loc.get('region_recall'))} "
            f"& {cell(loc.get('point_precision'))} "
            f"& {cell(m.get('parse_success_rate'))} \\\\"
        )
    body = "\n".join(rows)
    return f"""% Generated by make_paper_assets.py -- do not edit by hand.
\\begin{{tabular}}{{@{{}}lccc@{{}}}}
\\toprule
Category & Region recall & Point precision & Parse success \\\\
\\midrule
{body}
\\botrule
\\end{{tabular}}
"""


def table_ablation(sweep: Optional[Path]) -> str:
    if not sweep or not sweep.exists():
        return ("% No sweep summary found; run scripts/sweep.py first.\n"
                "% Table 3 in the manuscript retains its placeholders.\n")
    rows_raw = json.loads(sweep.read_text())
    grouped: Dict[str, Dict[str, List[dict]]] = {}
    for r in rows_raw:
        grouped.setdefault(r["sweep"], {}).setdefault(r["variant"], []).append(r)

    lines = []
    for sweep_name in sorted(grouped):
        variants = grouped[sweep_name]
        lines.append(f"\\multirow{{{len(variants)}}}{{*}}{{{sweep_name}}}")
        for i, variant in enumerate(sorted(variants)):
            entries = variants[variant]
            vals = [e["auroc_logical"] for e in entries
                    if isinstance(e.get("auroc_logical"), (int, float))]
            lats = [e["latency_p95"] for e in entries
                    if isinstance(e.get("latency_p95"), (int, float))]
            auroc = cell(sum(vals) / len(vals) if vals else None)
            lat = cell(sum(lats) / len(lats) if lats else None, places=2)
            prefix = "" if i == 0 else " "
            lines.append(f"{prefix} & {variant.replace('_', ' ')} & {auroc} & {lat} \\\\")
        lines.append("\\midrule")
    body = "\n".join(lines[:-1])
    return f"""% Generated by make_paper_assets.py -- do not edit by hand.
\\begin{{tabular}}{{@{{}}llcc@{{}}}}
\\toprule
Factor & Setting & AUROC$_{{\\mathrm{{log}}}}$ & Latency (s) \\\\
\\midrule
{body}
\\botrule
\\end{{tabular}}
"""


# -- figures -------------------------------------------------------------


def figure_shots(sweep: Optional[Path], out: Path) -> Optional[Path]:
    """Logical AUROC against reference-shot count, with per-category spread."""
    if not sweep or not sweep.exists():
        print("  skip fig_shots: no sweep summary")
        return None
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    rows = [r for r in json.loads(sweep.read_text()) if r["sweep"] == "shots"]
    if not rows:
        print("  skip fig_shots: no shot-count rows")
        return None

    by_k: Dict[int, List[float]] = {}
    for r in rows:
        try:
            k = int(str(r["variant"]).split("_")[-1])
        except ValueError:
            continue
        v = r.get("auroc_logical")
        if isinstance(v, (int, float)) and v == v:
            by_k.setdefault(k, []).append(v)
    if not by_k:
        print("  skip fig_shots: no usable values")
        return None

    ks = sorted(by_k)
    mean = [sum(by_k[k]) / len(by_k[k]) for k in ks]
    lo = [min(by_k[k]) for k in ks]
    hi = [max(by_k[k]) for k in ks]

    fig, ax = plt.subplots(figsize=(4.2, 2.9))
    ax.fill_between(ks, lo, hi, alpha=0.18, label="range across categories")
    ax.plot(ks, mean, marker="o", linewidth=1.8, label="mean")
    ax.set_xlabel("Reference shots $K$")
    ax.set_ylabel(r"AUROC$_{\mathrm{logical}}$")
    ax.set_xticks(ks)
    ax.grid(alpha=0.3, linewidth=0.5)
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    p = out / "fig_shots.pdf"
    fig.savefig(p, bbox_inches="tight")
    plt.close(fig)
    return p


def figure_qualitative(runs: Path, dataset: Optional[Path], out: Path,
                       per_category: int = 2) -> Optional[Path]:
    """Contact sheet of predicted defect coordinates over ground-truth regions."""
    if dataset is None:
        print("  skip fig_qualitative: pass --dataset to render overlays")
        return None
    import sys
    sys.path.insert(0, "src")
    try:
        from PIL import Image
        from keyprompt.data.loco import LocoCategory
        from keyprompt.viz import overlay, save_grid
    except ImportError as exc:
        print(f"  skip fig_qualitative: {exc}")
        return None

    panels: List[Image.Image] = []
    for key, _ in CATEGORIES:
        pred_file = runs / key / "predictions.jsonl"
        if not pred_file.exists():
            continue
        rows = [json.loads(l) for l in pred_file.read_text().splitlines() if l.strip()]
        anomalous = [r for r in rows if r["label"] == 1 and r.get("defect_points")]
        anomalous.sort(key=lambda r: -r["score"])
        try:
            cat = LocoCategory.open(dataset, key)
        except FileNotFoundError:
            continue
        by_uid = {s.uid: s for s in cat.test()}
        for r in anomalous[:per_category]:
            s = by_uid.get(r["uid"])
            if s is None:
                continue
            panels.append(
                overlay(s.load_image(), breakdown=r.get("breakdown"),
                        gt_mask=s.load_gt_union())
            )
    if not panels:
        print("  skip fig_qualitative: no predictions with defect points")
        return None
    p = out / "fig_qualitative.png"
    save_grid(panels, p, cols=4, cell=360)
    return p


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs", type=Path, required=True, help="run directory")
    ap.add_argument("--sweep", type=Path, default=None, help="sweep summary.json")
    ap.add_argument("--dataset", type=Path, default=None, help="MVTec LOCO root")
    ap.add_argument("--out", type=Path, default=Path("."))
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    metrics = load_metrics(args.runs)
    print(f"loaded metrics for {len(metrics)}/{len(CATEGORIES)} categories")
    if len(metrics) < len(CATEGORIES):
        missing = [k for k, _ in CATEGORIES if k not in metrics]
        print(f"  still to run: {', '.join(missing)}")
        print("  those rows will remain visible placeholders, not blanks")

    for name, text in [
        ("table_main.tex", table_main(metrics)),
        ("table_localisation.tex", table_localisation(metrics)),
        ("table_ablation.tex", table_ablation(args.sweep)),
    ]:
        (args.out / name).write_text(text)
        print(f"  wrote {args.out / name}")

    for p in (figure_shots(args.sweep, args.out),
              figure_qualitative(args.runs, args.dataset, args.out)):
        if p:
            print(f"  wrote {p}")

    print("\nPaste the generated tables into the manuscript, replacing the "
          "placeholder tabular blocks, then delete the \\needsdata macro so "
          "any remaining placeholder breaks the build.")


if __name__ == "__main__":
    main()
